// This file is autogenerated, do not edit here

extension Constants {
    struct images {
        static let badoo = "badoo"
        static let deviantart = "deviantart"
        static let dribbble = "dribbble"
        static let facebook = "facebook"
        static let flickr = "flickr"
        static let linked_in_1 = "linked in-1"
        static let twitter = "twitter"
        static let v_k = "v-k"
    }
}
