// This file is autogenerated, do not edit here

extension Constants {
    struct storyboards {
        struct launchScreen {
                static let name = "LaunchScreen"
                struct identifier {
                }
        }
        struct main {
                static let name = "Main"
                struct identifier {
                        static let mainViewController="mainViewController"
                        static let contentListTableViewController="contentListTableViewController"
                        static let privacyViewController="privacyViewController"
                }
        }
        struct home {
                static let name = "Home"
                struct identifier {
                }
        }
    }
}
