#!/bin/sh

#  defaultConstantsFileGeneration.sh
#  shellScriptStringGeneration
#
#  Created by Ankit Gupta on 12/31/16.
#  Copyright © 2016 ItKan. All rights reserved.

echo "-------------------- defaultConstantsFileGeneration.sh started --------------------"

#configure input variables for this script here
projectDir="$SRCROOT/shellScriptStringGeneration"
constantsDir="$projectDir/Constants"

# clean up current file
mkdir -p $constantsDir
rm $constantsDir/Constants.swift 2>/dev/null
touch $constantsDir/Constants.swift

# fill Constants.swift file with code
constantsFile="$constantsDir/Constants.swift"

echo "// This file is autogenerated, do not edit here" >> $constantsFile
echo "" >> $constantsFile
echo "struct Constants {" >> $constantsFile
echo "}" >> $constantsFile


echo "-------------------- defaultConstantsFileGeneration.sh stopped --------------------"
