#!/bin/sh

#  storyboardStringFileGeneration.sh
#  shellScriptStringGeneration
#
#  Created by Ankit Gupta on 12/31/16.
#  Copyright © 2016 ItKan. All rights reserved.

echo "-------------------- storyboardStringFileGeneration.sh started --------------------"

#configure input variables for script here
projectDir="$SRCROOT/shellScriptStringGeneration"
constantsDir="$projectDir/Constants"
outputFile="$constantsDir/Constants.storyboards.swift"

#declare dependent libraries here
commonLibSource="$projectDir/Build-phase/commonLib.sh"


rm tstoryboard*.* 2>/dev/null

# output file structure creation start
touch tstoryboard5.sh
echo "// This file is autogenerated, do not edit here" >> tstoryboard5.sh
echo "" >> tstoryboard5.sh
echo "extension Constants {" >> tstoryboard5.sh
echo "    struct storyboards {" >> tstoryboard5.sh


find $projectDir -type f -name *.storyboard -print0 | while IFS= read -r -d $'\0' line; do
fullname=`ls -1 "$line"`
storyboardName=`basename "$fullname" .storyboard`
structName=`source $commonLibSource; firstCharacterToLower $storyboardName`
echo "        struct $structName {" >> tstoryboard5.sh
echo "                static let name = \"$storyboardName\"" >> tstoryboard5.sh
echo "                struct identifier {" >> tstoryboard5.sh
storyboardIdentifierLine=`grep -n "storyboardIdentifier" "$fullname"`
for storyboardIdentifierPattern in `echo "$storyboardIdentifierLine" | sed 's/.*\(storyboardIdentifier="[a-zA-Z]*"\).*/\1/'`; do
storyboardIdentifier=`echo $storyboardIdentifierPattern | sed 's/.*\("[a-zA-Z]*"\).*/\1/'`
storyboardIdentifier=`echo $storyboardIdentifier | sed -e 's/^"//' -e 's/"$//'`
storyboardIdentifierVariable=`source $commonLibSource; firstCharacterToLower $storyboardIdentifier`

echo "                        static let $storyboardIdentifierVariable=\"$storyboardIdentifier\"" >> tstoryboard5.sh
done


echo "                }" >> tstoryboard5.sh
echo "        }" >> tstoryboard5.sh

done

# output file structure creation end
echo "    }" >> tstoryboard5.sh
echo "}" >> tstoryboard5.sh

rm $outputFile
mv tstoryboard5.sh $outputFile

rm tstoryboard*.* 2>/dev/null

echo "-------------------- storyboardStringFileGeneration.sh stopped --------------------"
