#!/bin/sh

#  xcAssetsStringFileGeneration.sh
#  shellScriptStringGeneration
#
#  Created by Ankit Gupta on 12/31/16.
#  Copyright © 2016 ItKan. All rights reserved.

echo "-------------------- xcAssetsStringFileGeneration.sh started --------------------"

#configure input variables for script here
projectDir="$SRCROOT/shellScriptStringGeneration"
constantsDir="$projectDir/Constants"
outputFile="$constantsDir/Constants.images.swift"
xcassets="$projectDir/Assets.xcassets"


cd $xcassets

#  remove any previously created temp files
rm txcassets*.* 2>/dev/null

#  find all imageset names
find . -type d -name '*.imageset' > txcassets1.sh
chmod 777 txcassets1.sh
sed -i -e 's/^/"/;s/$/"/' txcassets1.sh
sed -i -e 's/^/basename /' txcassets1.sh
sed -i -e 's/$/ .imageset/' txcassets1.sh
sh txcassets1.sh > txcassets2.sh
cp txcassets2.sh txcassets3.sh

#  create line as [static let phone = "phone"]
sed -i -e 's/-/_/' txcassets2.sh # replace - with _
sed -i -e 's/ /_/' txcassets2.sh # replace <space> with _
sed -i -e 's/^/"/;s/$/"/' txcassets3.sh
touch txcassets4.sh
:|paste -d ' = ' txcassets2.sh - - txcassets3.sh >> txcassets4.sh
sed -i -e 's/^/        static let /' txcassets4.sh
sort txcassets4.sh -o txcassets4.sh

#  add start / end lines
touch txcassets5.sh
echo "// This file is autogenerated, do not edit here" >> txcassets5.sh
echo "" >> txcassets5.sh
echo "extension Constants {" >> txcassets5.sh
echo "    struct images {" >> txcassets5.sh
cat txcassets4.sh >> txcassets5.sh
echo "    }" >> txcassets5.sh
echo "}" >> txcassets5.sh

rm $outputFile
mv txcassets5.sh $outputFile

#  remove any temp files created
rm txcassets*.* 2>/dev/null

echo "-------------------- xcAssetsStringFileGeneration.sh stopped --------------------"
